services:

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: minha_senha
      POSTGRES_DB: clientesdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"     
      - "15672:15672"   
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app-network

  cliente-service:
    build:
      context: ./ClienteService
      dockerfile: ./Dockerfile
    environment:
      postgre: Host=postgres;Port=5432;Username=postgres;Password=minha_senha;Database=clientesdb
      rabbitmq_url: rabbitmq
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "5080:8080"
    networks:
      - app-network

  credito-service:
    build:
      context: ./CreditoService
      dockerfile: ./Dockerfile
    environment:
      postgre: Host=postgres;Port=5432;Username=postgres;Password=minha_senha;Database=clientesdb
      rabbitmq_url: rabbitmq
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - app-network

  cartao-service:
    build:
      context: ./CartaoCreditoService
      dockerfile: ./Dockerfile
    environment:
      postgre: Host=postgres;Port=5432;Username=postgres;Password=minha_senha;Database=clientesdb
      rabbitmq_url: rabbitmq
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
